name: 'double-zero-proxy'
services:
  app:
    build:
      context: ..
      dockerfile: ./packages/app/Dockerfile
      args:
        VITE_API_URL: ${APP_API_URL}
        VITE_BRIDGE_URL: ${APP_BRIDGE_URL}
        VITE_HOSTNAMES: ${APP_HOSTNAMES}
        VITE_ICON: ${APP_ICON}
        VITE_L2_CHAIN_ID: ${APP_L2_CHAIN_ID}
        VITE_L2_NETWORK_NAME: ${APP_L2_NETWORK_NAME}
        VITE_MAINTENANCE: ${APP_MAINTENANCE}
        VITE_NAME: ${APP_NAME}
        VITE_PUBLISHED: ${APP_PUBLISHED}
        VITE_RPC_URL: ${APP_RPC_URL}
        VITE_BASE_TOKEN_ADDRESS: ${APP_BASE_TOKEN_ADDRESS}
        VITE_VERIFICATION_API_URL: ${VITE_VERIFICATION_API_URL}
    ports:
      - '3010:3010'
    depends_on:
      - proxy
    restart: unless-stopped

  proxy:
    build:
      context: ..
      dockerfile: ./packages/proxy/Dockerfile
    ports:
      - "4040:4040"
    environment:
      SERVER_PORT: 4040
      BLOCK_EXPLORER_API_URL: ${BLOCK_EXPLORER_API_URL}
      SESSION_SECRET: ${SESSION_SECRET}
      CORS_ORIGIN: ${CORS_ORIGIN_PROXY}
      RPC_URL: ${TARGET_RPC}
      USER_TOKEN_URL: http://private-rpc:4041/users
      CREATE_TOKEN_SECRET: ${CREATE_TOKEN_SECRET}

  private-rpc-migrate:
    build:
      context: ..
      dockerfile: ./packages/private-rpc/Dockerfile
    command: sh -c "yarn db:migrate"
    depends_on:
      db-private-rpc:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db-private-rpc:5432/private-rpc"

  private-rpc:
    build:
      context: ..
      dockerfile: ./packages/private-rpc/Dockerfile
    volumes:
      - ./compose-proxy-permissions.yaml:/app/permissions.yaml
    depends_on:
      db-private-rpc:
        condition: service_healthy
      private-rpc-migrate:
        condition: service_completed_successfully
    ports:
      - '4041:4041'
    environment:
      PORT: "4041"
      DATABASE_URL: "postgres://postgres:postgres@db-private-rpc:5432/private-rpc"
      TARGET_RPC: ${TARGET_RPC}
      PERMISSIONS_YAML_PATH: "/app/permissions.yaml"
      CORS_ORIGIN: ${CORS_ORIGIN_RPC}
      CREATE_TOKEN_SECRET: ${CREATE_TOKEN_SECRET}

  db-private-rpc:
    image: "postgres:14"
    logging:
      driver: none
    volumes:
      - db-private-rpc:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=private-rpc


volumes:
  db-private-rpc:
